version: '3.8'
services:
  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo
    container_name: zoo
    networks:
      - kafka_network
    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
# 0.0.0.0     PLAINTEXT://localhost:9092
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    networks:
      - kafka_network

    ports:
      - "29093:29093"
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENERS: INTERNAL://:9092,MINIKUBE://:29092,XPOSED_TO_HOST_MACHINE_APPS://:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,MINIKUBE://192.168.49.2:29092,XPOSED_TO_HOST_MACHINE_APPS://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,MINIKUBE:PLAINTEXT,XPOSED_TO_HOST_MACHINE_APPS:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo

networks:
  kafka_network:
    name: kafka_docker_example_net