---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-productservice
spec:
  type: ClusterIP
  selector:
    app: ecommerce-productservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
